In [1]:
pip install hmmlearn



     ---------------------------------------- 0.0/123.6 kB ? eta -:--:--
     --- ------------------------------------ 10.2/123.6 kB ? eta -:--:--
     --------- --------------------------- 30.7/123.6 kB 262.6 kB/s eta 0:00:01
     --------- --------------------------- 30.7/123.6 kB 262.6 kB/s eta 0:00:01
     --------- --------------------------- 30.7/123.6 kB 262.6 kB/s eta 0:00:01
     ------------------ ------------------ 61.4/123.6 kB 252.2 kB/s eta 0:00:01
     ------------------ ------------------ 61.4/123.6 kB 252.2 kB/s eta 0:00:01
     --------------------------- --------- 92.2/123.6 kB 275.8 kB/s eta 0:00:01
     --------------------------- --------- 92.2/123.6 kB 275.8 kB/s eta 0:00:01
     ------------------------------------ 123.6/123.6 kB 302.4 kB/s eta 0:00:00


In [2]:
from sklearn import datasets
from hmmlearn import hmm
import numpy as np


Generated Samples:
[[6.19365433 2.37538942 4.60051216 1.49208094]
 [5.51833397 3.04326802 3.33748003 1.01466201]
 [5.78482612 3.08289271 3.03221315 0.99557766]
 [4.61667351 3.16368942 1.64853639 0.43524062]
 [5.57876282 2.76761876 2.82296875 0.68061339]]


C:\Users\91705\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1436: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(



# Loading Iris dataset

In [3]:
iris = datasets.load_iris()
X = iris.data


# Training the HMM model

In [4]:
model = hmm.GaussianHMM(n_components=3, covariance_type="full", n_iter=100)
model.fit(X)

C:\Users\91705\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1436: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


GaussianHMM(covariance_type='full', n_components=3, n_iter=100)

# Generating a sequence of observations from the model

In [5]:
generated_samples, _ = model.sample(5)

print("Generated Samples:")
print(generated_samples)


Generated Samples:
[[4.88120012 3.48944664 1.32021833 0.0754042 ]
 [5.02549041 3.97321263 1.79482102 0.27919467]
 [5.11717646 3.63455046 1.49398509 0.19593315]
 [4.63540504 3.07614143 1.57615249 0.26518418]
 [5.33043408 3.963462   1.35873586 0.25403837]]
